/*
 * Automatically generated C config: don't edit
 */
#define RTCONFIG_OPTIMIZE_SHARED_LIBS 1
#define RTCONFIG_L2TP 1
#define RTCONFIG_PPTP 1
#define RTCONFIG_EAPOL 1
#undef RTCONFIG_PPTPD
#define RTCONFIG_ACCEL_PPTPD 1
#undef RTCONFIG_SNMPD
#define RTCONFIG_HTTPS 1
#define RTCONFIG_BCMARM 1
#undef RTCONFIG_BCM7
#undef RTCONFIG_BCM_794
#undef RTCONFIG_BCM_7114
#undef RTCONFIG_BCM10
#define RTCONFIG_BCM9 1
#undef RTCONFIG_BUILDBCM7
#undef RTCONFIG_ROMCFE
#undef RTCONFIG_ROMATECCODEFIX
#undef RTCONFIG_NV128
#undef RTCONFIG_DHDAP
#define RTCONFIG_WLEXE 1
#undef RTCONFIG_DPSTA
#undef RTCONFIG_GMAC3
#undef RTCONFIG_BCMSMP
#undef RTCONFIG_BCMFA
#undef RTCONFIG_RGMII_BCM_FA
#undef RTCONFIG_5301X
#undef RTCONFIG_4352_5G
#define RTCONFIG_SSH 1
#undef RTCONFIG_CIFS
#undef RTCONFIG_BRCM_NAND_JFFS2
#define RTCONFIG_JFFS2 1
#undef RTCONFIG_DISKTEST
#undef RTCONFIG_JFFSV1
#undef RTCONFIG_ZEBRA
#define RTCONFIG_QUAGGA 1
#define RTCONFIG_DDNS 1
#undef RTCONFIG_L7
#undef RTCONFIG_LZO
#define RTCONFIG_IPV6 1
#define RTCONFIG_EBTABLES 1
#define RTCONFIG_EMF 1
#undef RTCONFIG_BCMBSD
#undef RTCONFIG_BCMSSD
#define RTCONFIG_BCMDCS 1
#undef RTCONFIG_TOAD
#undef RTCONFIG_HSPOT
#undef RTCONFIG_FANCTRL
#define RTCONFIG_BCMWL6 1
#define RTCONFIG_BCMWL6A 1
#undef RTCONFIG_WIRELESSWAN
#define RTCONFIG_WIRELESSREPEATER 1
#define RTCONFIG_DISABLE_REPEATER_UI 1
#define RTCONFIG_PROXYSTA 1
#undef RTCONFIG_CONCURRENTREPEATER
#undef RTCONFIG_IXIAEP
#undef RTCONFIG_IPERF
#undef RTCONFIG_TCPDUMP
#define RTCONFIG_PARENTALCTRL 1
#define RTCONFIG_YANDEXDNS 1
#undef RTCONFIG_DSL
#undef RTCONFIG_DSL_ANNEX_B
#undef RTCONFIG_DSL_TCLINUX
#undef RTCONFIG_VDSL
#define RTCONFIG_DUALWAN 1
#undef RTCONFIG_HW_DUALWAN
#define RTCONFIG_USER_LOW_RSSI 1
#undef RTCONFIG_NEW_USER_LOW_RSSI
#undef RTCONFIG_PUSH_EMAIL
#define RTCONFIG_USB 1
#undef RTCONFIG_USBRESET
#undef RTCONFIG_WIFIPWR
#undef RTCONFIG_XHCIMODE
#undef RTCONFIG_MEDIA_SERVER
#undef RTCONFIG_CLOUDSYNC
#define RTCONFIG_FTP 1
#undef RTCONFIG_FTP_SSL
#undef RTCONFIG_WEBDAV
#define RTCONFIG_SAMBASRV 1
#define RTCONFIG_SAMBA3 1
#define RTCONFIG_USB_EXTRAS 1
#undef RTCONFIG_TFAT
#undef RTCONFIG_NTFS
#undef RTCONFIG_HFS
#define RTCONFIG_DISK_MONITOR 1
#undef RTCONFIG_USB_PRINTER
#define RTCONFIG_USB_MODEM 1
#undef RTCONFIG_USB_LESSMODEM
#define RTCONFIG_USB_MODEM_PIN 1
#undef RTCONFIG_USB_SMS_MODEM
#undef RTCONFIG_USB_BECEEM
#define RTCONFIG_BRCM_USBAP 1
#undef RTCONFIG_APP_PREINSTALLED
#undef RTCONFIG_APP_NETINSTALLED
#undef RTCONFIG_RALINK
#undef RTCONFIG_RALINK_MT7621
#undef RTCONFIG_NEWSSID_REV2
#undef RTCONFIG_QCA
#undef RTCONFIG_QCA953X
#undef RTCONFIG_QCA956X
#undef RTCONFIG_QCA_PLC_UTILS
#undef RTCONFIG_AR7420
#undef RTCONFIG_QCA7500
#undef RTCONFIG_DEFAULT_AP_MODE
#define RTCONFIG_ODMPID 1
#undef RTCONFIG_TIMEMACHINE
#define RTCONFIG_MDNS 1
#undef RTCONFIG_FINDASUS
#undef RTCONFIG_REDIRECT_DNAME
#undef RTCONFIG_MTK_TW_AUTO_BAND4
#undef RTCONFIG_QCA_TW_AUTO_BAND4
#undef RTCONFIG_LED_ALL
#undef RTCONFIG_COMA
#define CONFIG_LIBBCM 1
#define CONFIG_LIBUPNP 1
#define RTCONFIG_WPS 1
#undef RTCONFIG_WPS_ENROLLEE
#define RTCONFIG_SHP 1
#undef RTCONFIG_SFP
#undef RTCONFIG_STRACE
#undef RTCONFIG_4M_SFP
#undef RTCONFIG_8M_SFP
#undef RTCONFIG_16M_RAM_SFP
#define RTCONFIG_GROCTRL 1
#undef RTCONFIG_LANWAN_LED
#undef RTCONFIG_WLAN_LED
#undef RTCONFIG_FAKE_ETLAN_LED
#undef RTCONFIG_EXT_LED_WPS
#undef RTCONFIG_SWMODE_SWITCH
#undef RTCONFIG_WL_AUTO_CHANNEL
#undef RTCONFIG_SMALL_FW_UPDATE
#undef RTCONFIG_WIRELESS_SWITCH
#undef RTCONFIG_WIFI_TOG_BTN
#undef RTCONFIG_WPS_RST_BTN
#define RTCONFIG_WPS_ALLLED_BTN 1
#undef RTCONFIG_LOGO_LED
#undef RTCONFIG_LED_BTN
#undef RTCONFIG_USBEJECT
#define RTCONFIG_AUTODICT 1
#undef RTCONFIG_AUTOLIVEUPDATE_ZIP
#undef RTCONFIG_ISP_METER
#define RTCONFIG_NVRAM_64K 1
#undef RTCONFIG_USB_XHCI
#undef RTCONFIG_WLMODULE_RT3090_AP
#undef RTCONFIG_WLMODULE_RT3352_INIC_MII
#undef RTCONFIG_WLMODULE_MT7610_AP
#undef RTCONFIG_WLMODULE_RLT_WIFI
#undef RTCONFIG_WLMODULE_MT7603E_AP
#undef RTCONFIG_PSISTLOG
#undef RTCONFIG_DUAL_TRX
#undef RTCONFIG_UBI
#undef RTCONFIG_UBIFS
#define RTCONFIG_OPTIMIZE_XBOX 1
#undef RTCONFIG_NEW_REGULATION_DOMAIN
#undef RTCONFIG_DYN_DICT_NAME
#undef RTCONFIG_LAN4WAN_LED
#undef RTCONFIG_EXT4FS
#undef RTCONFIG_DMALLOC
#undef RTCONFIG_JFFS2ND_BACKUP
#define RTCONFIG_TEMPROOTFS 1
#undef RTCONFIG_ATEUSB3_FORCE
#define RTCONFIG_JFFS2LOG 1
#undef RTCONFIG_WPSMULTIBAND
#undef RTCONFIG_RALINK_DFS
#undef RTCONFIG_ENGINEERING_MODE
#define RTCONFIG_VPNC 1
#undef RTCONFIG_KYIVSTAR
#undef RTCONFIG_ETRON_XHCI
#undef RTCONFIG_ETRON_XHCI_USB3_LED
#undef RTCONFIG_WPS_LED
#undef RTCONFIG_MMC_LED
#undef RTCONFIG_RESET_SWITCH
#undef RTCONFIG_WANRED_LED
#undef RTCONFIG_BLINK_LED
#undef RTCONFIG_CFE_NVRAM_CHK
#undef RTCONFIG_DEBUG
#undef RTCONFIG_LLDP
#define RTCONFIG_HAS_5G 1
#undef RTCONFIG_TFTP
#undef RTCONFIG_QTN
#undef RTCONFIG_WPS_DUALBAND
#undef RTCONFIG_N18UTXBF
#undef RTCONFIG_BWDPI
#undef RTCONFIG_ADBLOCK
#undef RTCONFIG_TRAFFIC_LIMITER
#define RTCONFIG_SPEEDTEST 1
#undef RTCONFIG_BONDING
#undef RTCONFIG_UIDEBUG
#undef RTCONFIG_ROG
#undef RTCONFIG_GEOIP
#undef RTCONFIG_TRANSMISSION
#undef RTCONFIG_NOWL
#define RTCONFIG_TCODE 1
#undef RTCONFIG_ALLNOWL
#undef RTCONFIG_WIFILOGO
#define RTCONFIG_JFFS2USERICON 1
#undef RTCONFIG_EXT_RTL8365MB
#undef RTCONFIG_EXT_RTL8370MB
#undef RTCONFIG_TOR
#undef RTCONFIG_TR069
#undef RTCONFIG_TR181
#undef RTCONFIG_STAINFO
#undef RTCONFIG_CLOUDCHECK
#define RTCONFIG_GETREALIP 1
#undef RTCONFIG_TUNNEL
#undef RTCONFIG_CFEZ
#undef RTCONFIG_RESTRICT_GUI
#undef RTCONFIG_LACP
#undef RTCONFIG_KEY_GUARD
#undef RTCONFIG_RECVFILE
#undef RTCONFIG_WTFAST
#undef RTCONFIG_IFTTT
#undef RTCONFIG_ERP_TEST
#undef RTCONFIG_REBOOT_SCHEDULE
#undef RTCONFIG_INTERNAL_GOBI
#define RTCONFIG_UPNPC 1
#define RTCONFIG_MULTICAST_IPTV 1
#define RTCONFIG_BONJOUR 1
#undef RTCONFIG_FBWIFI
#undef RTCONFIG_FORCE_AUTO_UPGRADE
#undef RTCONFIG_TUXERA_SMBD
#undef RTCONFIG_BCMASPMD
#undef RTCONFIG_WLCLMLOAD
#undef RTCONFIG_MUMIMO
#undef RTCONFIG_DYN_MODEM
#undef RTCONFIG_NOTIFICATION_CENTER
#define RTCONFIG_6RELAYD 1
#undef RTCONFIG_PORT_BASED_VLAN
#undef RTCONFIG_NOIPTV
#define RTCONFIG_AUTOCOVER_SIP 1
#define RTCONFIG_DEFLAN50 1
#undef RTCONFIG_WLCEVENTD
